Drop support for python 2 and FIX: #22 - AttributeError: module 'docutils.nodes' has no attribute '… (#23)
* FIX: #22 - AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'. reprunicode is a compatibility hack for python 2. It has been removed from docutils in v0.21.

* Update __init__.py - fix typo

* Drop python 2 support