FIX: #22 - AttributeError: module 'docutils.nodes' has no attribute 'reprunicode'. reprunicode is a compatibility hack for python 2. It has been removed from docutils in v0.21.